"""Layer-B numerical conformance tests against SOM_PAK golden files (FR-8).

ADR-0001 layer B: run the full somkit pipeline (randinit -> train_pak two-phase)
with the same parameters/seeds as SOM_PAK and compare the resulting codebook and
quantization error against committed golden files (generated by
``test/golden/regenerate.sh``). CI never runs the C binaries; it only compares.

Tolerances: the golden ``.cod`` stores ~6 significant digits; the measured max
abs diff is ~7e-4 (FP ordering variation). ``atol=1e-2`` gives ~14x headroom to
absorb future SOM_PAK version / cross-platform float-ordering differences;
tightening to 1e-3 would leave only ~1.4x margin. ``qerror rtol=1e-2`` matches
the ~1e-6 relative error of the 6-digit ``.cod`` representation.

References:
    - command.sh (hexa/bubble, randinit -rand 123, vsom -rand 1)
    - som_rout.c:680-733 (find_qerror)
"""

import os

import numpy as np
import pytest

from somkit import SOMTrainer
from somkit.data_loader import load_som_pak_data
from somkit.evaluator import SOMEvaluator
from somkit.functions import OrandRNG, random_init

from ._cod import read_cod, read_qerror

GOLDEN = os.path.join(os.path.dirname(__file__), "golden")

XDIM, YDIM = 10, 10
INIT_SEED = 123
ORDER_SEED = 1
ATOL = 1e-2
QERROR_RTOL = 1e-2

# Training parameters — must match test/golden/regenerate.sh exactly.
PHASE1 = dict(
    rlen=1000, alpha=0.05, radius=10.0,
    neighborhood="bubble", random_order=True, seed=ORDER_SEED,
)
PHASE2 = dict(
    rlen=2000, alpha=0.02, radius=3.0,
    neighborhood="bubble", random_order=True, seed=ORDER_SEED,
)

# Skip the whole module if golden files are absent (run regenerate.sh first).
pytestmark = pytest.mark.skipif(
    not os.path.exists(os.path.join(GOLDEN, "ex_init.cod")),
    reason="golden files missing; run `bash test/golden/regenerate.sh`",
)


def _load_data():
    # ex.dat (dim=5) has no per-row label; somkit's load_som_pak_data would drop
    # the last column as a label and yield 4 dims, breaking SOM_PAK parity. Read
    # all 5 numeric columns directly so the data matches what randinit/vsom saw.
    return np.loadtxt(
        os.path.join(GOLDEN, "ex.dat"), skiprows=1, usecols=range(5), dtype=np.float64
    )


def _new_trainer(data):
    # learning_rate is unused by train_pak (which takes its own alpha); it only
    # satisfies the constructor signature.
    return SOMTrainer(
        data=data,
        size=(XDIM, YDIM),
        input_dim=data.shape[1],
        learning_rate=0.05,
        topology="hexagonal",
    )


# ----------------------------------------------------------------------
# Parser fixture itself
# ----------------------------------------------------------------------
class TestCodParser:
    def test_header_and_shape(self):
        header, weights = read_cod(os.path.join(GOLDEN, "ex_init.cod"))
        assert header == {
            "dim": 5,
            "topol": "hexa",
            "xdim": 10,
            "ydim": 10,
            "neigh": "bubble",
        }
        assert weights.shape == (10, 10, 5)

    def test_qerror_parse(self):
        qe = read_qerror(os.path.join(GOLDEN, "qerror.txt"))
        assert qe > 0.0


# ----------------------------------------------------------------------
# Layer B: randinit
# ----------------------------------------------------------------------
def test_randinit_matches_som_pak():
    data = _load_data()
    _, golden = read_cod(os.path.join(GOLDEN, "ex_init.cod"))
    weights = random_init(data, XDIM, YDIM, OrandRNG(INIT_SEED))
    np.testing.assert_allclose(weights, golden, atol=ATOL)


# ----------------------------------------------------------------------
# Layer B: training (phase 1, phase 2)
# ----------------------------------------------------------------------
def test_phase1_matches_som_pak():
    data = _load_data()
    _, golden = read_cod(os.path.join(GOLDEN, "ex_phase1.cod"))
    som = _new_trainer(data)
    som.weights = random_init(data, XDIM, YDIM, OrandRNG(INIT_SEED))
    som.train_pak(**PHASE1)
    np.testing.assert_allclose(som.weights, golden, atol=ATOL)


def test_two_phase_matches_som_pak():
    data = _load_data()
    _, golden = read_cod(os.path.join(GOLDEN, "ex_trained.cod"))
    som = _new_trainer(data)
    som.weights = random_init(data, XDIM, YDIM, OrandRNG(INIT_SEED))
    som.train_two_phase(phase1=PHASE1, phase2=PHASE2)
    np.testing.assert_allclose(som.weights, golden, atol=ATOL)


# ----------------------------------------------------------------------
# Layer B: quantization error
# ----------------------------------------------------------------------
def test_qerror_matches_som_pak():
    data = _load_data()
    golden_qe = read_qerror(os.path.join(GOLDEN, "qerror.txt"))
    som = _new_trainer(data)
    som.weights = random_init(data, XDIM, YDIM, OrandRNG(INIT_SEED))
    som.train_two_phase(phase1=PHASE1, phase2=PHASE2)
    qe = SOMEvaluator(som).calculate_quantization_error()
    assert qe == pytest.approx(golden_qe, rel=QERROR_RTOL)


# ----------------------------------------------------------------------
# Layer B: vcal label calibration (FR-5)
# ----------------------------------------------------------------------
def _read_cod_labels(path, x_size, dim):
    """Parse per-unit label tokens (after the `dim` components) into a grid."""
    rows = []
    header = None
    with open(path) as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            if header is None:
                header = line
                continue
            rows.append(line.split()[dim:])
    assert len(rows) % x_size == 0, "vector count not a multiple of x_size"
    grid = np.empty((x_size, len(rows) // x_size), dtype=object)
    for k, labs in enumerate(rows):
        grid[k % x_size, k // x_size] = labs
    return grid


@pytest.mark.skipif(
    not os.path.exists(os.path.join(GOLDEN, "animal_cal.cod")),
    reason="animal vcal golden missing; run `bash test/golden/regenerate.sh`",
)
def test_vcal_matches_som_pak():
    bunch = load_som_pak_data(os.path.join(GOLDEN, "animal.dat"))
    data = np.asarray(bunch.data, dtype=np.float64)
    som = SOMTrainer(
        data=bunch, size=(5, 5), input_dim=16, learning_rate=0.05, topology="hexagonal"
    )
    som.weights = random_init(data, 5, 5, OrandRNG(INIT_SEED))
    som.train_pak(
        rlen=1000, alpha=0.05, radius=5.0,
        neighborhood="bubble", random_order=True, seed=ORDER_SEED,
    )
    grid = som.calibrate_labels(numlabs=1)
    golden = _read_cod_labels(os.path.join(GOLDEN, "animal_cal.cod"), 5, 16)
    for x in range(5):
        for y in range(5):
            assert grid[x, y] == list(golden[x, y]), f"unit ({x}, {y})"
